### ISSUE TITLE
Crash with Latest WTFOres and IC2

### ISSUE THREAD

**Issue by DoughnutDev** [WhiskyTangoFawks/WTFOres#1]
I have tried everything but for some reason you can not add IC2 Ores with WTFOres. Also when join it a world it spams Adding Block and breaks MultiMC so may want to disable that or have an option.

**Comment by DoughnutDev** [comment]
http://pastebin.com/VwHQYZuv Crash Log

**Comment by WhiskyTangoFawks** [comment]
Based on the crash log, it looks like IC2 may be doing some of it's own reflection to the texture atlas, which prevents WTFores from generating the textures correctly.

**Comment by DoughnutDev** [comment]
Also is there away to disable the Adding Blocks spam. Like add it in a debug mode.

**Comment by WhiskyTangoFawks** [comment]
That was debug logging I forgot to disable- it's already been fixed, and you can download a new version from curseforge.
